### ISSUE TITLE
Failure to build project dependant on compiler-util

### ISSUE THREAD

**Issue by Rovanion** [nx-js/compiler-util#11]
When trying to make a production build of a project which depends on @nx-js/compiler-util using create-react-apps build system I get the following error:

```
Failed to minify the code from this file: 

 	./node_modules/@nx-js/compiler-util/src/modifiers.js:7 

Read more here: http://bit.ly/2tRViJ9
```

Following that link I'm instructed to ask you to publish a new version of your package to npm, but with ES6 features compiled out of the source code and replaced by ES5 analogues. Can I assist you in any way to reach the point where you can do this?

**Comment by solkimicreb** [comment]
Hey, this library is a bit behind in infrastructure than my others. I will update it to have an es5 build in the afternoon. You won't have to do anything, it will work after that.

(The lib uses unpolyfillable Proxies so it is inherently es6 only, but create-react-app 1 uses an older version of uglifyjs which does not understand es6 code. It is pretty awkward to transpile the code only for the minifier, but modern JS can be strange sometimes 😄)

**Comment by Rovanion** [comment]
Thank you so much!

**Comment by solkimicreb** [comment]
Hi!

I updated the lib and bumped the major version just to be sure. You can get the `2.0.0` release from npm which is transpiled to es5 by default. Changelog is here: https://github.com/nx-js/compiler-util/releases/tag/v2.0.0.

Closing the issue, please reopen if you still have issues with this 🙂
